import type { KPIMetric } from '@/types'

/** Large primary KPI cards - Total beneficiaries & Capital deployed */
export const KPI_PRIMARY: KPIMetric[] = [
  {
    id: 'total-beneficiaries',
    label: 'Total beneficiaries reached',
    value: 12.4,
    unit: 'M',
    change: 34,
    changePeriod: 'vs last quarter',
    trend: 'up',
    sparklineData: [9.1, 9.5, 10.0, 10.4, 10.9, 11.2, 11.6, 12.4],
    color: '#ffffff',
    chartColor: '#94a3b8',
    description: 'Total people reached by water solutions',
    hasDarkBackground: true,
  },
  {
    id: 'total-capital',
    label: 'Total Capital deployed',
    value: 450,
    prefix: '$',
    unit: 'M',
    change: 34,
    changePeriod: 'vs last quarter',
    trend: 'up',
    sparklineData: [330, 350, 365, 380, 395, 410, 435, 450],
    color: '#1e293b',
    chartColor: '#2F446A',
    description: 'Total capital deployed across deployments',
    hasDarkBackground: false,
  },
]

/** Secondary metric cards */
export const KPI_SECONDARY: KPIMetric[] = [
  {
    id: 'water-secured',
    label: 'Water Secured',
    value: 850.4,
    unit: 'M',
    change: 34,
    changePeriod: '7 days',
    trend: 'up',
    sparklineData: [720, 750, 770, 790, 810, 830, 840, 850.4],
    color: '#1677ff',
    description: 'Cubic meters of water secured',
    showPeriodDropdown: true,
  },
  {
    id: 'economic-impact',
    label: 'Economic impact',
    value: 2.1,
    prefix: '$',
    unit: 'B',
    change: 62,
    changePeriod: 'vs last quarter',
    trend: 'up',
    sparklineData: [1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1],
    color: '#22c55e',
    description: 'Economic impact in billions',
  },
  {
    id: 'productivity-index',
    label: 'Productivity improvement index',
    value: 25,
    unit: '%',
    change: 50,
    changePeriod: 'vs last quarter',
    trend: 'up',
    sparklineData: [18, 19, 20, 21, 22, 23, 24, 25],
    color: '#1677ff',
    description: 'Productivity improvement percentage',
  },
  {
    id: 'health-indicators',
    label: 'Health improvement indicators',
    value: 31,
    unit: '%',
    change: 21,
    changePeriod: 'vs last quarter',
    trend: 'up',
    sparklineData: [26, 27, 28, 29, 29.5, 30, 30.5, 31],
    color: '#f59e0b',
    description: 'Health improvement percentage',
  },
]
