import type { KPIMetric } from '@/shared/types'

/** Large primary KPI cards - Total beneficiaries & Capital deployed */
export const KPI_PRIMARY: KPIMetric[] = [
  {
    id: 'total-beneficiaries',
    label: 'Total beneficiaries reached',
    value: 12.4,
    unit: 'M',
    change: 34,
    changePeriod: 'vs last quarter',
    trend: 'up',
    sparklineData: [9.1, 9.8, 9.3, 30.6, 9.8, 41.1, 5.4, 60.4],
    color: '#ffffff',
    chartColor: '#94a3b8',
    description: 'Total people reached by water solutions',
    hasDarkBackground: true,
  },
  {
    id: 'total-capital',
    label: 'Total Capital deployed',
    value: 450,
    prefix: '$',
    unit: 'M',
    change: 34,
    changePeriod: 'vs last quarter',
    trend: 'up',
    // Dummy pattern to mimic alternating up/down spikes in the reference screenshot
    sparklineData: [330, 200, 540, 120, 600, 300, 760, 450],
    color: '#1e293b',
    chartColor: '#2F446A',
    description: 'Total capital deployed across deployments',
    hasDarkBackground: false,
  },
]

/** Secondary row: penultimate bar is the visual peak; last bar = current headline value */
export const KPI_SECONDARY: KPIMetric[] = [
  {
    id: 'water-secured',
    label: 'Water Secured',
    value: 850.4,
    unit: 'M',
    change: 34,
    changePeriod: '7 days',
    trend: 'up',
    sparklineData: [620, 655, 640, 705, 735, 780, 920, 850.4],
    color: '#2e4362',
    chartColor: '#2e4362',
    description: 'Cubic meters of water secured',
    showPeriodDropdown: true,
  },
  {
    id: 'economic-impact',
    label: 'Economic impact',
    value: 2.1,
    prefix: '$',
    unit: 'B',
    change: 62,
    changePeriod: 'vs last quarter',
    trend: 'up',
    sparklineData: [0.95, 1.05, 1.15, 1.28, 1.42, 1.58, 2.48, 2.1],
    color: '#15803d',
    chartColor: '#15803d',
    description: 'Economic impact in billions',
  },
  {
    id: 'productivity-index',
    label: 'Productivity improvement index',
    value: 25,
    unit: '%',
    change: 50,
    changePeriod: 'vs last quarter',
    trend: 'up',
    sparklineData: [12, 14, 15, 17, 18, 20, 30, 25],
    color: '#0284c7',
    chartColor: '#38bdf8',
    description: 'Productivity improvement percentage',
  },
  {
    id: 'health-indicators',
    label: 'Health improvement indicators',
    value: 31,
    unit: '%',
    change: 21,
    changePeriod: 'vs last quarter',
    trend: 'up',
    sparklineData: [19, 21, 22, 24, 26, 27, 38, 31],
    color: '#ea580c',
    chartColor: '#fb923c',
    description: 'Health improvement percentage',
  },
]
