import type { MapMarker } from '@/shared/types'

export const MAP_MARKERS: MapMarker[] = [
  // Africa
  { id: 'nga', country: 'Nigeria', capital: 'Abuja', lat: 9.0579, lng: 7.4951, riskLevel: 'high', riskScore: 7.8, region: 'West Africa', population: '220M', metrics: { stability: 42, economic: 55, security: 38, environmental: 61 }, activeOperations: 12, lastIncident: '2 days ago', trend: 'declining', deploymentStatus: 'in_progress', waterScarcity: 72, capitalDeployed: 85, impactScore: 78, infrastructure: 45 },
  { id: 'eth', country: 'Ethiopia', capital: 'Addis Ababa', lat: 9.0240, lng: 38.7469, riskLevel: 'high', riskScore: 7.2, region: 'East Africa', population: '120M', metrics: { stability: 45, economic: 48, security: 41, environmental: 55 }, activeOperations: 8, lastIncident: '5 days ago', trend: 'stable', deploymentStatus: 'deployed', waterScarcity: 65, capitalDeployed: 45, impactScore: 72, infrastructure: 52 },
  { id: 'ken', country: 'Kenya', capital: 'Nairobi', lat: -1.2921, lng: 36.8219, riskLevel: 'low', riskScore: 5.2, region: 'East Africa', population: '55M', metrics: { stability: 60, economic: 65, security: 58, environmental: 63 }, activeOperations: 6, lastIncident: '1 week ago', trend: 'improving', deploymentStatus: 'deployed', waterScarcity: 55, capitalDeployed: 62, impactScore: 85, infrastructure: 68 },
  { id: 'moz', country: 'Mozambique', capital: 'Maputo', lat: -25.9629, lng: 32.5732, riskLevel: 'medium', riskScore: 5.8, region: 'Southern Africa', population: '33M', metrics: { stability: 55, economic: 58, security: 52, environmental: 60 }, activeOperations: 5, lastIncident: '2 weeks ago', trend: 'improving', deploymentStatus: 'in_progress', waterScarcity: 58, capitalDeployed: 28, impactScore: 62, infrastructure: 55 },
  { id: 'sdn', country: 'Sudan', capital: 'Khartoum', lat: 15.5007, lng: 32.5599, riskLevel: 'critical', riskScore: 9.1, region: 'Northeast Africa', population: '44M', metrics: { stability: 22, economic: 31, security: 20, environmental: 42 }, activeOperations: 15, lastIncident: 'Today', trend: 'declining', deploymentStatus: 'pending', waterScarcity: 82 },
  { id: 'mli', country: 'Mali', capital: 'Bamako', lat: 12.6392, lng: -8.0029, riskLevel: 'high', riskScore: 8.1, region: 'West Africa', population: '22M', metrics: { stability: 35, economic: 40, security: 32, environmental: 48 }, activeOperations: 9, lastIncident: '1 day ago', trend: 'declining', deploymentStatus: 'pending', waterScarcity: 75 },
  { id: 'gha', country: 'Ghana', capital: 'Accra', lat: 5.5600, lng: -0.1969, riskLevel: 'low', riskScore: 3.2, region: 'West Africa', population: '32M', metrics: { stability: 75, economic: 72, security: 78, environmental: 70 }, activeOperations: 2, lastIncident: '1 month ago', trend: 'improving', deploymentStatus: 'deployed', waterScarcity: 42, capitalDeployed: 35, impactScore: 90, infrastructure: 72 },
  { id: 'cod', country: 'DR Congo', capital: 'Kinshasa', lat: -4.4419, lng: 15.2663, riskLevel: 'high', riskScore: 7.9, region: 'Central Africa', population: '100M', metrics: { stability: 38, economic: 42, security: 35, environmental: 52 }, activeOperations: 11, lastIncident: '3 days ago', trend: 'stable', deploymentStatus: 'in_progress', waterScarcity: 68 },
  { id: 'cmr', country: 'Cameroon', capital: 'Yaoundé', lat: 3.8480, lng: 11.5021, riskLevel: 'medium', riskScore: 5.9, region: 'Central Africa', population: '27M', metrics: { stability: 53, economic: 56, security: 50, environmental: 58 }, activeOperations: 4, lastIncident: '10 days ago', trend: 'stable', deploymentStatus: 'deployed', waterScarcity: 52 },
  { id: 'egy', country: 'Egypt', capital: 'Cairo', lat: 30.0444, lng: 31.2357, riskLevel: 'medium', riskScore: 5.4, region: 'North Africa', population: '102M', metrics: { stability: 58, economic: 62, security: 54, environmental: 47 }, activeOperations: 7, lastIncident: '4 days ago', trend: 'stable', deploymentStatus: 'in_progress', waterScarcity: 61, capitalDeployed: 40, impactScore: 66, infrastructure: 50 },
  // South Asia
  { id: 'ind', country: 'India', capital: 'New Delhi', lat: 28.6139, lng: 77.2090, riskLevel: 'low', riskScore: 3.8, region: 'South Asia', population: '1.4B', metrics: { stability: 70, economic: 75, security: 68, environmental: 62 }, activeOperations: 3, lastIncident: '3 weeks ago', trend: 'improving', deploymentStatus: 'deployed', waterScarcity: 68, capitalDeployed: 120, impactScore: 88, infrastructure: 62, activeDeployment: 'Rainwater Harvesting Infrastructure - Maintain' },
  { id: 'pak', country: 'Pakistan', capital: 'Islamabad', lat: 33.7294, lng: 73.0931, riskLevel: 'high', riskScore: 7.5, region: 'South Asia', population: '230M', metrics: { stability: 42, economic: 50, security: 40, environmental: 55 }, activeOperations: 14, lastIncident: '2 days ago', trend: 'stable', deploymentStatus: 'in_progress', waterScarcity: 78 },
  { id: 'bgd', country: 'Bangladesh', capital: 'Dhaka', lat: 23.8103, lng: 90.4125, riskLevel: 'medium', riskScore: 5.4, region: 'South Asia', population: '170M', metrics: { stability: 58, economic: 61, security: 55, environmental: 45 }, activeOperations: 4, lastIncident: '2 weeks ago', trend: 'stable', deploymentStatus: 'deployed', waterScarcity: 62 },
  { id: 'npl', country: 'Nepal', capital: 'Kathmandu', lat: 27.7172, lng: 85.3240, riskLevel: 'low', riskScore: 3.1, region: 'South Asia', population: '30M', metrics: { stability: 72, economic: 60, security: 74, environmental: 55 }, activeOperations: 1, lastIncident: '2 months ago', trend: 'improving', deploymentStatus: 'deployed', waterScarcity: 45 },
  { id: 'lka', country: 'Sri Lanka', capital: 'Colombo', lat: 6.9271, lng: 79.8612, riskLevel: 'medium', riskScore: 4.8, region: 'South Asia', population: '22M', metrics: { stability: 60, economic: 55, security: 62, environmental: 65 }, activeOperations: 3, lastIncident: '3 weeks ago', trend: 'improving', deploymentStatus: 'in_progress', waterScarcity: 55 },
  { id: 'afg', country: 'Afghanistan', capital: 'Kabul', lat: 34.5553, lng: 69.2075, riskLevel: 'critical', riskScore: 9.4, region: 'South Asia', population: '39M', metrics: { stability: 18, economic: 25, security: 16, environmental: 28 }, activeOperations: 10, lastIncident: 'Today', trend: 'declining', deploymentStatus: 'pending', waterScarcity: 88, capitalDeployed: 22, impactScore: 58, infrastructure: 32, activeDeployment: 'Emergency Borehole Stabilization - Verify & Repair' },
  // Southeast Asia
  { id: 'mmr', country: 'Myanmar', capital: 'Naypyidaw', lat: 19.7633, lng: 96.0785, riskLevel: 'critical', riskScore: 8.9, region: 'Southeast Asia', population: '55M', metrics: { stability: 25, economic: 38, security: 22, environmental: 48 }, activeOperations: 16, lastIncident: 'Yesterday', trend: 'declining', deploymentStatus: 'pending', waterScarcity: 72 },
  { id: 'idn', country: 'Indonesia', capital: 'Jakarta', lat: -6.2088, lng: 106.8456, riskLevel: 'medium', riskScore: 4.9, region: 'Southeast Asia', population: '275M', metrics: { stability: 63, economic: 67, security: 60, environmental: 52 }, activeOperations: 4, lastIncident: '2 weeks ago', trend: 'improving', deploymentStatus: 'deployed', waterScarcity: 58, capitalDeployed: 55, impactScore: 75, infrastructure: 58 },
  { id: 'tha', country: 'Thailand', capital: 'Bangkok', lat: 13.7563, lng: 100.5018, riskLevel: 'low', riskScore: 3.5, region: 'Southeast Asia', population: '70M', metrics: { stability: 72, economic: 74, security: 70, environmental: 65 }, activeOperations: 2, lastIncident: '1 month ago', trend: 'stable', deploymentStatus: 'deployed', waterScarcity: 48 },
  { id: 'vnm', country: 'Vietnam', capital: 'Hanoi', lat: 21.0285, lng: 105.8542, riskLevel: 'low', riskScore: 3.0, region: 'Southeast Asia', population: '98M', metrics: { stability: 75, economic: 78, security: 73, environmental: 60 }, activeOperations: 1, lastIncident: '6 weeks ago', trend: 'improving', deploymentStatus: 'in_progress', waterScarcity: 52 },
  { id: 'phl', country: 'Philippines', capital: 'Manila', lat: 14.5995, lng: 120.9842, riskLevel: 'medium', riskScore: 5.6, region: 'Southeast Asia', population: '115M', metrics: { stability: 57, economic: 62, security: 54, environmental: 50 }, activeOperations: 5, lastIncident: '1 week ago', trend: 'stable', deploymentStatus: 'deployed', waterScarcity: 62 },
  // South America (Brazil for Agritech)
  { id: 'bra', country: 'Brazil', capital: 'Brasília', lat: -15.7801, lng: -47.9292, riskLevel: 'low', riskScore: 4.2, region: 'South America', population: '215M', metrics: { stability: 65, economic: 70, security: 68, environmental: 60 }, activeOperations: 4, lastIncident: '2 weeks ago', trend: 'improving', deploymentStatus: 'in_progress', waterScarcity: 55, capitalDeployed: 72, impactScore: 80, infrastructure: 65 },
]
